import type {ListingCatalogResponse} from "#shared/types/response.types";

export const listings: ListingCatalogResponse[] = [
    {
        id: 1,
        title: 'etgsgsdg',
        photos: ['/hero.png', '/hero.png', '/hero.png', '/hero.png',],
        rooms: 1,
        area: 50,
        type: 'flat',
        places: 3,
        price: 5000,
    },
    {
        id: 2,
        title: 'etgsgsdg',
        photos: ['/hero.png'],
        rooms: 1,
        area: 50,
        type: 'flat',
        places: 3,
        price: 5000,
    },
    {
        id: 3,
        title: 'etgsgsdg',
        photos: ['/hero.png'],
        rooms: 1,
        area: 50,
        type: 'flat',
        places: 3,
        price: 5000,
    },
    {
        id: 1,
        title: 'etgsgsdg',
        photos: ['/hero.png', '/hero.png', '/hero.png', '/hero.png',],
        rooms: 1,
        area: 50,
        type: 'flat',
        places: 3,
        price: 5000,
    },
    {
        id: 2,
        title: 'etgsgsdg',
        photos: ['/hero.png'],
        rooms: 1,
        area: 50,
        type: 'flat',
        places: 3,
        price: 5000,
    },
    {
        id: 3,
        title: 'etgsgsdg',
        photos: ['/hero.png'],
        rooms: 1,
        area: 50,
        type: 'flat',
        places: 3,
        price: 5000,
    }
];